FROM haproxy:2.3

RUN apt update
RUN apt install -y net-tools procps curl wget iproute2 iputils-ping

COPY haproxy-olap.cfg /usr/local/etc/haproxy/haproxy.cfg

RUN mkdir -p /run/haproxy && chmod 660 /run/haproxy

