version: '1.0'

services:

  haproxy:
    container_name: haproxy
    image: roach-haproxy
    ports:
      - "8080:8080"
      - "26257:26257"
    # volumes:
    #   - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/hapropxy


  roach0:
    container_name: roach0
    image: cockroachdb/cockroach
    # ports:
    #   - "8080:8080"
    #   - "26257:26257"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/roach0/data:/data
    command: start --insecure --listen-addr=roach0:26257 --join=roach0:26257,roach1:26257,roach2:26257 --http-addr=roach0:8080 --store=/data
    

  roach1:
    container_name: roach1
    image: cockroachdb/cockroach
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/roach1/data:/data
    command: start --insecure --listen-addr=roach1:26257 --join=roach0:26257,roach1:26257,roach2:26257 --http-addr=roach1:8080 --store=/data
    

  roach2:
    container_name: roach2
    image: cockroachdb/cockroach
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/roach2/data:/data
    command: start --insecure --listen-addr=roach2:26257 --join=roach0:26257,roach1:26257,roach2:26257 --http-addr=roach2:8080 --store=/data
    

  roach3:
    container_name: roach3
    image: cockroachdb/cockroach
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/roach3/data:/data
    command: start --insecure --listen-addr=roach3:26257 --join=roach0:26257,roach1:26257,roach2:26257 --http-addr=roach3:8080 --store=/data
    

  roach4:
    container_name: roach4
    image: cockroachdb/cockroach
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/roach4/data:/data
    command: start --insecure --listen-addr=roach4:26257 --join=roach0:26257,roach1:26257,roach2:26257 --http-addr=roach4:8080 --store=/data
    

  roach5:
    container_name: roach5
    image: cockroachdb/cockroach
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/roach5/data:/data
    command: start --insecure --listen-addr=roach5:26257 --join=roach0:26257,roach1:26257,roach2:26257 --http-addr=roach5:8080 --store=/data
    

  roachinit:
    container_name: roachinit
    image: cockroachdb/cockroach
    depends_on:
      - roach0
      - roach1
      - roach2
    restart: "no"
    command: init --host roach0:26257 --insecure

