services:

  alertmanager:
    restart: always
    container_name: alertmanager
    image: prom/alertmanager
    ports:
      - "9093:9093"
    deploy:
      placement:
        constraints:
          - node.labels.region == centcomm
    


  prometheus:
    restart: always
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/grafana:/etc/prometheus
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/prometheus:/prometheus
    deploy:
      placement:
        constraints:
          - node.labels.region == centcomm



  grafana:
    restart: always
    container_name: grafana
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/grafana:/var/lib/grafana
    deploy:
      placement:
        constraints:
          - node.labels.region == centcomm

