services:

    haproxy-one:
      image: localhost:5000/haproxy_multi_region_one
      build:
        context: .
        dockerfile: Dockerfile.haproxy-multi-region-one
      command:
        - roach-one-0
        - roach-one-1
        - roach-one-2
      ports:
        - "8082:8080"
        - "26259:26257"
      deploy:
        restart_policy:
          delay: 10s
        placement:
          constraints:
            - node.labels.region == centcomm


    haproxy-two:
      image: localhost:5000/haproxy_multi_region_two
      build:
        context: .
        dockerfile: Dockerfile.haproxy-multi-region-two
      command:
        - roach-two-0
        - roach-two-1
        - roach-two-2
      ports:
        - "8083:8080"
        - "26260:26257"
      deploy:
        restart_policy:
          delay: 10s
        placement:
          constraints:
            - node.labels.region == centcomm


    haproxy-three:
      image: localhost:5000/haproxy_multi_region_three
      build:
        context: .
        dockerfile: Dockerfile.haproxy-multi-region-three
      command:
        - roach-three-0
        - roach-three-1
        - roach-three-2
      ports:
        - "8084:8080"
        - "26261:26257"
      deploy:
        restart_policy:
          delay: 10s
        placement:
          constraints:
            - node.labels.region == centcomm


    roach-one-0:
      container_name: roach-one-0
      image: cockroachdb/cockroach
      volumes:
        - /mnt/volumes/certs/multi-region:/cockroach/certs
        - /mnt/volumes/multi-region/one/0/data:/data
      command: start --certs-dir=/cockroach/certs --listen-addr=tasks.roach-one-0:26258 --sql-addr=tasks.roach-one-0:26257 --join=tasks.roach-one-0:26258,tasks.roach-one-1:26258,tasks.roach-one-2:26258 --http-addr=tasks.roach-one-0:8080 --store=/data --locality=region=one
      deploy:
        placement:
          constraints:
            - node.labels.multi-region == one


    roach-one-1:
      container_name: roach-one-1
      image: cockroachdb/cockroach
      volumes:
        - /mnt/volumes/certs/multi-region:/cockroach/certs
        - /mnt/volumes/multi-region/one/1/data:/data
      command: start --certs-dir=/cockroach/certs --listen-addr=tasks.roach-one-1:26258 --sql-addr=tasks.roach-one-1:26257 --join=tasks.roach-one-0:26258,tasks.roach-one-1:26258,tasks.roach-one-2:26258 --http-addr=tasks.roach-one-1:8080 --store=/data --locality=region=one
      deploy:
        placement:
          constraints:
            - node.labels.multi-region == one


    roach-one-2:
      container_name: roach-one-2
      image: cockroachdb/cockroach
      volumes:
        - /mnt/volumes/certs/multi-region:/cockroach/certs
        - /mnt/volumes/multi-region/one/2/data:/data
      command: start --certs-dir=/cockroach/certs --listen-addr=tasks.roach-one-2:26258 --sql-addr=tasks.roach-one-2:26257 --join=tasks.roach-one-0:26258,tasks.roach-one-1:26258,tasks.roach-one-2:26258 --http-addr=tasks.roach-one-2:8080 --store=/data --locality=region=one
      deploy:
        placement:
          constraints:
            - node.labels.multi-region == one



    roachinit:
      image: cockroachdb/cockroach
      volumes:
        - /mnt/volumes/certs/multi-region:/cockroach/certs
      command: init --host tasks.roach-one-0:26257
      deploy:
        restart_policy:
          max_attempts: 6
          delay: 10s
        placement:
          constraints:
            - node.labels.region == centcomm



    roach-two-0:
      container_name: roach-two-0
      image: cockroachdb/cockroach
      volumes:
        - /mnt/volumes/certs/multi-region:/cockroach/certs
        - /mnt/volumes/multi-region/two/0/data:/data
      command: start --certs-dir=/cockroach/certs --listen-addr=tasks.roach-two-0:26258 --sql-addr=tasks.roach-two-0:26257 --join=tasks.roach-one-0:26258,tasks.roach-one-1:26258,tasks.roach-one-2:26258 --http-addr=tasks.roach-two-0:8080 --store=/data --locality=region=two
      deploy:
        placement:
          constraints:
            - node.labels.multi-region == two


    roach-two-1:
      container_name: roach-two-1
      image: cockroachdb/cockroach
      volumes:
        - /mnt/volumes/certs/multi-region:/cockroach/certs
        - /mnt/volumes/multi-region/two/1/data:/data
      command: start --certs-dir=/cockroach/certs --listen-addr=tasks.roach-two-1:26258 --sql-addr=tasks.roach-two-1:26257 --join=tasks.roach-one-0:26258,tasks.roach-one-1:26258,tasks.roach-one-2:26258 --http-addr=tasks.roach-two-1:8080 --store=/data --locality=region=two
      deploy:
        placement:
          constraints:
            - node.labels.multi-region == two


    roach-two-2:
      container_name: roach-two-2
      image: cockroachdb/cockroach
      volumes:
        - /mnt/volumes/certs/multi-region:/cockroach/certs
        - /mnt/volumes/multi-region/two/2/data:/data
      command: start --certs-dir=/cockroach/certs --listen-addr=tasks.roach-two-2:26258 --sql-addr=tasks.roach-two-2:26257 --join=tasks.roach-one-0:26258,tasks.roach-one-1:26258,tasks.roach-one-2:26258 --http-addr=tasks.roach-two-2:8080 --store=/data --locality=region=two
      deploy:
        placement:
          constraints:
            - node.labels.multi-region == two


    roach-three-0:
      container_name: roach-three-0
      image: cockroachdb/cockroach
      volumes:
        - /mnt/volumes/certs/multi-region:/cockroach/certs
        - /mnt/volumes/multi-region/three/0/data:/data
      command: start --certs-dir=/cockroach/certs --listen-addr=tasks.roach-three-0:26258 --sql-addr=tasks.roach-three-0:26257 --join=tasks.roach-one-0:26258,tasks.roach-one-1:26258,tasks.roach-one-2:26258 --http-addr=tasks.roach-three-0:8080 --store=/data --locality=region=three
      deploy:
        placement:
          constraints:
            - node.labels.region == eu-central-1


    roach-three-1:
      container_name: roach-three-1
      image: cockroachdb/cockroach
      volumes:
        - /mnt/volumes/certs/multi-region:/cockroach/certs
        - /mnt/volumes/multi-region/three/1/data:/data
      command: start --certs-dir=/cockroach/certs --listen-addr=tasks.roach-three-1:26258 --sql-addr=tasks.roach-three-1:26257 --join=tasks.roach-one-0:26258,tasks.roach-one-1:26258,tasks.roach-one-2:26258 --http-addr=tasks.roach-three-1:8080 --store=/data --locality=region=three
      deploy:
        placement:
          constraints:
            - node.labels.region == eu-central-1


    roach-three-2:
      container_name: roach-three-2
      image: cockroachdb/cockroach
      volumes:
        - /mnt/volumes/certs/multi-region:/cockroach/certs
        - /mnt/volumes/multi-region/three/2/data:/data
      command: start --certs-dir=/cockroach/certs --listen-addr=tasks.roach-three-2:26258 --sql-addr=tasks.roach-three-2:26257 --join=tasks.roach-one-0:26258,tasks.roach-one-1:26258,tasks.roach-one-2:26258 --http-addr=tasks.roach-three-2:8080 --store=/data --locality=region=three
      deploy:
        placement:
          constraints:
            - node.labels.region == eu-central-1


